import { GetStaticPaths, GetStaticProps } from 'next';
import { getDivisionRecord } from '@/utils/get-division-record';
import dataImported from '@/store/data.json';
import { BeerLists } from '@/layouts/beer-lists';
import Head from 'next/head';

const Page = (props: any) => {
  const { prefectures } = props;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=M+PLUS+1p:wght@300;400;500;800;900&display=swap"
          rel="stylesheet"
        />
      </Head>
      <BeerLists prefectures={prefectures} />
    </>
  );
};

export default Page;

type Prefecture = {
  prefecture: string;
  beers: Beers;
};

type Props = {
  prefectures: Prefecture[];
};

type Beers = {
  name: string;
  style: string;
  color: string;
  alcohol: number;
  bitterness: string;
  sweetness: string;
  fullBodied: string;
  feature: string;
}[];

type Regions = {
  [key: string]: {
    prefectures: {
      prefecture: string;
      beers: Beers;
    }[];
  };
};

export const getStaticProps: GetStaticProps<Props> = async (props) => {
  const { division } = getDivisionRecord(props);
  const data: Regions = dataImported;

  return {
    props: data[division],
  };
};

export const getStaticPaths: GetStaticPaths = async () => {
  const divisions = ['hokkaidou-touhoku', 'kantou', 'tyubu', 'kinki', 'tyugoku', 'kyusyu'];

  const paths = divisions.map((division) => {
    return { params: { division } };
  });

  return { paths, fallback: false };
};
